name: Check for docker warnings
on:
  - pull_request
defaults:
  run:
    shell: bash # making this explicit opts into -e -o pipefail
jobs:
  check_docker_warnings:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run checker
      run: .github/workflows/check-docker.sh
