name: Trigger Private AppArmor Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apparmor/**/*'

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
        - name: Generate Temporary GitHub App Token
          uses: actions/create-github-app-token@v2.0.2
          id: generate_token
          with:
            app-id: ${{ secrets.GH_APP_ID }}
            private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

        - name: Trigger AppArmor Workflow in a Private Repository
          uses: actions/github-script@v7.0.1
          env:
            OWNER: ${{ secrets.GH_APPARMOR_TRIGGER_OWNER }}
            REPO: ${{ secrets.GH_APPARMOR_TRIGGER_REPO }}
            WORKFLOW_ID: ${{ secrets.GH_APPARMOR_TRIGGER_WORKFLOW_ID }}
          with:
            github-token: ${{ steps.generate_token.outputs.token }}
            script: |
                await github.rest.actions.createWorkflowDispatch({
                  owner: process.env.OWNER,
                  repo: process.env.REPO,
                  workflow_id: process.env.WORKFLOW_ID,
                  ref: 'master'
                });
